export const common = [
  { label: "Day Generation Cumulative (KWH)", checked: true },
  { label: "Power Generation Instant (MW)", checked: true },
  { label: "Peak Power", checked: true },
  { label: "Plant PR Instant", checked: true },
  { label: "GA Instant", checked: true },
  { label: "PA Instant", checked: true },
  { label: "GHI Instant", checked: true },
  { label: "GTI Instant", checked: true },
  { label: "GHI Instant 2", checked: true },
  { label: "GTI Instant 2", checked: true },
  { label: "Amb. Temp Instant", checked: true },
  { label: "Amb. Temp Instant 2", checked: true },
  { label: "Mod. Temp Instant", checked: true },
  { label: "Mod. Temp Instant 2", checked: true },
  { label: "Wind Speed Instant", checked: true },
  { label: "Wind Speed Instant 2", checked: true },
  { label: "Wind Dir Instant", checked: true },
  { label: "Wind Dir Instant 2", checked: true },
  { label: "Humidity Instant", checked: true },
  { label: "Humidity Instant 2", checked: true },
  { label: "Rain", checked: true },
  { label: "Rain 2", checked: true },
];

export const uncheckedCommon = [
  { label: "Day Generation Cumulative (KWH)", checked: false },
  { label: "Power Generation Instant (MW)", checked: false },
  { label: "Peak Power", checked: false },
  { label: "Plant PR Instant", checked: false },
  { label: "GA Instant", checked: false },
  { label: "PA Instant", checked: false },
  { label: "GHI Instant", checked: false },
  { label: "GTI Instant", checked: false },
  { label: "GHI Instant 2", checked: false },
  { label: "GTI Instant 2", checked: false },
  { label: "Amb. Temp Instant", checked: false },
  { label: "Amb. Temp Instant 2", checked: false },
  { label: "Mod. Temp Instant", checked: false },
  { label: "Mod. Temp Instant 2", checked: false },
  { label: "Wind Speed Instant", checked: false },
  { label: "Wind Speed Instant 2", checked: false },
  { label: "Wind Dir Instant", checked: false },
  { label: "Wind Dir Instant 2", checked: false },
  { label: "Humidity Instant", checked: false },
  { label: "Humidity Instant 2", checked: false },
  { label: "Rain", checked: false },
  { label: "Rain 2", checked: false },
];

export const inverters = [
  { label: "L1 I", checked: true },
  { label: "L2 I", checked: true },
  { label: "L3 I", checked: true },
  { label: "L1 V", checked: true },
  { label: "L2 V", checked: true },
  { label: "L3 V", checked: true },
  { label: "Frequency", checked: true },
  { label: "DC I", checked: true },
  { label: "DC V", checked: true },
  { label: "Active Power", checked: true },
  { label: "DC Power", checked: true },
  { label: "Reactive Power", checked: true },
  { label: "PF", checked: true },
  { label: "Cab Temp", checked: true },
  { label: "IGBT Temp", checked: true },
  { label: "DC Energy", checked: true },
];

export const uncheckedInverters = [
  { label: "L1 I", checked: false },
  { label: "L2 I", checked: false },
  { label: "L3 I", checked: false },
  { label: "L1 V", checked: false },
  { label: "L2 V", checked: false },
  { label: "L3 V", checked: false },
  { label: "Frequency", checked: false },
  { label: "DC I", checked: false },
  { label: "DC V", checked: false },
  { label: "Active Power", checked: false },
  { label: "DC Power", checked: false },
  { label: "Reactive Power", checked: false },
  { label: "PF", checked: false },
  { label: "Cab Temp", checked: false },
  { label: "IGBT Temp", checked: false },
  { label: "DC Energy", checked: false },
];

export const inverterSlots = [
  { label: "S1 L2 I", checked: true },
  { label: "S1 L1 I", checked: true },
  { label: "S1 L3 I", checked: true },
  { label: "S1 L1 V", checked: true },
  { label: "S1 L2 V", checked: true },
  { label: "S1 L3 V", checked: true },
  { label: "S1 DC I", checked: true },
  { label: "S1 DC V", checked: true },
  { label: "S1 Active Power", checked: true },
  { label: "S1 DC Power", checked: true },
  { label: "S1 PF", checked: true },
  { label: "S1 Cab Temp", checked: true },
  { label: "S1 IGBT Temp", checked: true },
  { label: "S2 L1 I", checked: true },
  { label: "S2 L2 I", checked: true },
  { label: "S2 L3 I", checked: true },
  { label: "S2 L1 V", checked: true },
  { label: "S2 L2 V", checked: true },
  { label: "S2 L3 V", checked: true },
  { label: "S2 DC I", checked: true },
  { label: "S2 DC V", checked: true },
  { label: "S2 Active Power", checked: true },
  { label: "S2 DC Power", checked: true },
  { label: "S2 PF", checked: true },
  { label: "S2 Cab Temp", checked: true },
  { label: "S2 IGBT Temp", checked: true },
  { label: "S3 L1 I", checked: true },
  { label: "S3 L2 I", checked: true },
  { label: "S3 L3 I", checked: true },
  { label: "S3 L1 V", checked: true },
  { label: "S3 L2 V", checked: true },
  { label: "S3 L3 V", checked: true },
  { label: "S3 DC I", checked: true },
  { label: "S3 DC V", checked: true },
  { label: "S3 Active Power", checked: true },
  { label: "S3 DC Power", checked: true },
  { label: "S3 PF", checked: true },
  { label: "S3 Cab Temp", checked: true },
  { label: "S3 IGBT Temp", checked: true },
  { label: "S4 L1 I", checked: true },
  { label: "S4 L2 I", checked: true },
  { label: "S4 L3 I", checked: true },
  { label: "S4 L1 V", checked: true },
  { label: "S4 L2 V", checked: true },
  { label: "S4 L3 V", checked: true },
  { label: "S4 DC I", checked: true },
  { label: "S4 DC V", checked: true },
  { label: "S4 Active Power", checked: true },
  { label: "S4 DC Power", checked: true },
  { label: "S4 PF", checked: true },
  { label: "S4 Cab Temp", checked: true },
  { label: "S4 IGBT Temp", checked: true },
  { label: "S1 + S2 Peak Active Power", checked: true },
  { label: "S3 + S4 Peak Active Power", checked: true },
];

export const uncheckedInverterSlots = [
  { label: "S1 L2 I", checked: false },
  { label: "S1 L1 I", checked: false },
  { label: "S1 L3 I", checked: false },
  { label: "S1 L1 V", checked: false },
  { label: "S1 L2 V", checked: false },
  { label: "S1 L3 V", checked: false },
  { label: "S1 DC I", checked: false },
  { label: "S1 DC V", checked: false },
  { label: "S1 Active Power", checked: false },
  { label: "S1 DC Power", checked: false },
  { label: "S1 PF", checked: false },
  { label: "S1 Cab Temp", checked: false },
  { label: "S1 IGBT Temp", checked: false },
  { label: "S2 L1 I", checked: false },
  { label: "S2 L2 I", checked: false },
  { label: "S2 L3 I", checked: false },
  { label: "S2 L1 V", checked: false },
  { label: "S2 L2 V", checked: false },
  { label: "S2 L3 V", checked: false },
  { label: "S2 DC I", checked: false },
  { label: "S2 DC V", checked: false },
  { label: "S2 Active Power", checked: false },
  { label: "S2 DC Power", checked: false },
  { label: "S2 PF", checked: false },
  { label: "S2 Cab Temp", checked: false },
  { label: "S2 IGBT Temp", checked: false },
  { label: "S3 L1 I", checked: false },
  { label: "S3 L2 I", checked: false },
  { label: "S3 L3 I", checked: false },
  { label: "S3 L1 V", checked: false },
  { label: "S3 L2 V", checked: false },
  { label: "S3 L3 V", checked: false },
  { label: "S3 DC I", checked: false },
  { label: "S3 DC V", checked: false },
  { label: "S3 Active Power", checked: false },
  { label: "S3 DC Power", checked: false },
  { label: "S3 PF", checked: false },
  { label: "S3 Cab Temp", checked: false },
  { label: "S3 IGBT Temp", checked: false },
  { label: "S4 L1 I", checked: false },
  { label: "S4 L2 I", checked: false },
  { label: "S4 L3 I", checked: false },
  { label: "S4 L1 V", checked: false },
  { label: "S4 L2 V", checked: false },
  { label: "S4 L3 V", checked: false },
  { label: "S4 DC I", checked: false },
  { label: "S4 DC V", checked: false },
  { label: "S4 Active Power", checked: false },
  { label: "S4 DC Power", checked: false },
  { label: "S4 PF", checked: false },
  { label: "S4 Cab Temp", checked: false },
  { label: "S4 IGBT Temp", checked: false },
  { label: "S1 + S2 Peak Active Power", checked: false },
  { label: "S3 + S4 Peak Active Power", checked: false },
];

export const inverterStrings = [
  { label: "S1 / S1CB1 I", checked: true },
  { label: "S2 / S1CB2 I", checked: true },
  { label: "S3 / S1CB3 I", checked: true },
  { label: "S4 / S1CB4 I", checked: true },
  { label: "S5 / S1CB5 I", checked: true },
  { label: "S6 / S1CB6 I", checked: true },
  { label: "S7 / S1CB7 I", checked: true },
  { label: "S8 / S1CB8 I", checked: true },
  { label: "S9 / S2CB1 I", checked: true },
  { label: "S10 / S2CB2 I", checked: true },
  { label: "S11 / S2CB3 I", checked: true },
  { label: "S12 / S2CB4 I", checked: true },
  { label: "S13 / S2CB5 I", checked: true },
  { label: "S14 / S2CB6 I", checked: true },
  { label: "S15 / S2CB7 I", checked: true },
  { label: "S16 / S2CB8 I", checked: true },
  { label: "S17 / S3CB1 I", checked: true },
  { label: "S18 / S3CB2 I", checked: true },
  { label: "S19 / S3CB3 I", checked: true },
  { label: "S20 / S3CB4 I", checked: true },
  { label: "S21 / S3CB5 I", checked: true },
  { label: "S22 / S3CB6 I", checked: true },
  { label: "S23 / S3CB7 I", checked: true },
  { label: "S24 / S3CB8 I", checked: true },
  { label: "S25 / S4CB1 I", checked: true },
  { label: "S26 / S4CB2 I", checked: true },
  { label: "S27 / S4CB3 I", checked: true },
  { label: "S28 / S4CB4 I", checked: true },
  { label: "S29 / S4CB5 I", checked: true },
  { label: "S30 / S4CB6 I", checked: true },
  { label: "S31 / S4CB7 I", checked: true },
  { label: "S32 / S4CB8 I", checked: true },
];

export const uncheckedInverterStrings = [
  { label: "S1 / S1CB1 I", checked: false },
  { label: "S2 / S1CB2 I", checked: false },
  { label: "S3 / S1CB3 I", checked: false },
  { label: "S4 / S1CB4 I", checked: false },
  { label: "S5 / S1CB5 I", checked: false },
  { label: "S6 / S1CB6 I", checked: false },
  { label: "S7 / S1CB7 I", checked: false },
  { label: "S8 / S1CB8 I", checked: false },
  { label: "S9 / S2CB1 I", checked: false },
  { label: "S10 / S2CB2 I", checked: false },
  { label: "S11 / S2CB3 I", checked: false },
  { label: "S12 / S2CB4 I", checked: false },
  { label: "S13 / S2CB5 I", checked: false },
  { label: "S14 / S2CB6 I", checked: false },
  { label: "S15 / S2CB7 I", checked: false },
  { label: "S16 / S2CB8 I", checked: false },
  { label: "S17 / S3CB1 I", checked: false },
  { label: "S18 / S3CB2 I", checked: false },
  { label: "S19 / S3CB3 I", checked: false },
  { label: "S20 / S3CB4 I", checked: false },
  { label: "S21 / S3CB5 I", checked: false },
  { label: "S22 / S3CB6 I", checked: false },
  { label: "S23 / S3CB7 I", checked: false },
  { label: "S24 / S3CB8 I", checked: false },
  { label: "S25 / S4CB1 I", checked: false },
  { label: "S26 / S4CB2 I", checked: false },
  { label: "S27 / S4CB3 I", checked: false },
  { label: "S28 / S4CB4 I", checked: false },
  { label: "S29 / S4CB5 I", checked: false },
  { label: "S30 / S4CB6 I", checked: false },
  { label: "S31 / S4CB7 I", checked: false },
  { label: "S32 / S4CB8 I", checked: false },
];
