// export const siteNamesCaps = [
//     'Balanagar',
//     'Balangir',
//     'Banka M',
//     'Banka N',
//     'Bazpur',
//     'Bhadla L2',
//     'Bhadla L3',
//     'Bhongir',
//     'Bidar',
//     'Bikaner',
//     'Byagwat',
//     'Chattisgarh',
//     'Chittorgarh',
//     'Chittuguppa',
//     'Farhatabad',
//     'Gadarpur',
//     'Godhur',
//     'Gulelgudda',
//     'Hindupur',
//     'Hukkeri',
//     'Jhandekalan',
//     'Jhunir',
//     'Khambhat',
//     'Kherakhurd',
//     'Khilchipur',
//     'Kittur',
//     'Kosigi',
//     'Kudligi',
//     'Maddur',
//     'Mahoba',
//     'Mankhera',
//     'Manthani',
//     'Mothkur',
//     'Nangla',
//     'Padmajiwadi',
//     'Pattikonda',
//     'Rayachoti',
//     'Sadashivpet',
//     'Sandur',
//     'Santhipuram',
//     'Sidlaghatta',
//     // 'Sircilla',
//     'Yemmiganur',
//   ];

//   export const siteNamesAndBlocks = [
//     {name: 'Balanagar', blocks: [8]},
//     {name: 'Balangir', blocks: [9]},
//     {name: 'Banka M', blocks: [2]},
//     {name: 'Banka N', blocks: [4]},
//     {name: 'Bazpur', blocks: [6]},
//     {name: 'Bhadla L2', blocks: [14]},
//     {name: 'Bhadla L3', blocks: [14]},
//     {name: 'Bhongir', blocks: [10]},
//     {name: 'Bidar', blocks: [8]},
//     {name: 'Bikaner', blocks: [1]},
//     {name: 'Byagwat', blocks: [8]},
//     {name: 'Chattisgarh', blocks: [7]},
//     {name: 'Chittorgarh', blocks: [34]},
//     {name: 'Chittuguppa', blocks: [8]},
//     {name: 'Farhatabad', blocks: [8]},
//     {name: 'Gadarpur', blocks: [6]},
//     {name: 'Godhur', blocks: [2]},
//     {name: 'Gulelgudda', blocks: [2]},
//     {name: 'Hindupur', blocks: [13]},
//     {name: 'Hukkeri', blocks: [2]},
//     {name: 'Jhandekalan', blocks: [5]},
//     {name: 'Jhunir', blocks: [3]},
//     {name: 'Khambhat', blocks: [15]},
//     {name: 'Kherakhurd', blocks: [5]},
//     {name: 'Khilchipur', blocks: [10]},
//     {name: 'Kittur', blocks: [2]},
//     {name: 'Kosigi', blocks: [2]},
//     {name: 'Kudligi', blocks: [3]},
//     {name: 'Maddur', blocks: [7]},
//     {name: 'Mahoba', blocks: [5]},
//     {name: 'Mankhera', blocks: [5]},
//     {name: 'Manthani', blocks: [2]},
//     {name: 'Mothkur', blocks: [2]},
//     {name: 'Nangla', blocks: [3]},
//     {name: 'Padmajiwadi', blocks: [2]},
//     {name: 'Pattikonda', blocks: [5]},
//     {name: 'Rayachoti', blocks: [5]},
//     {name: 'Sadashivpet', blocks: [10]},
//     {name: 'Sandur', blocks: [3]},
//     {name: 'Santhipuram', blocks: [10]},
//     {name: 'Sidlaghatta', blocks: [3]},
//     // {name: 'Sircilla', blocks: [6]},
//     {name: 'Yemmiganur', blocks: [7]},
//   ];

//   // export const tempSitesBlocksInverters = [
//   //   {name: 'Balanagar', blocks: [{name: 'B01', inverters: [{name: 1}, {name: 2}]}, {name: 'B02', inverters: [{name: 1}, {name: 2}]}]},
//   //   {name: 'Balangir', blocks: [{name: 'B01', inverters: [{name: 1}, {name: 2}]}, {name: 'B02', inverters: [{name: 1}, {name: 2}]}, {name: 'B03', inverters: [{name: 1}, {name: 2}]}]},
//   // ];

export const tempSitesBlocksInverters = [
  { name: "Balanagar", blocks: [{ name: "B01", inverters: [{ name: 1 }] }] },
];

export const siteNamesCaps = [];
export const siteNamesAndBlocks = [];
